apiVersion: v1
kind: Service
metadata:
  name: ${DOMAIN_NAME}-mysql
  labels:
    app: ${DOMAIN_NAME}-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: ${DOMAIN_NAME}-mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: ${DOMAIN_NAME}-mysql-read
  labels:
    app: ${DOMAIN_NAME}-mysql-read
spec:
  ports:
  - name: ${DOMAIN_NAME}-mysql
    port: 3306
  selector:
    app: ${DOMAIN_NAME}-mysql

