apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mydomain-mysql
spec:
  serviceName: mydomain-mysql
  replicas: 3
  selector:
    matchLabels:
      app: mydomain-mysql
  template:
    metadata:
      labels:
        app: mydomain-mysql
    spec:
      containers:
      - name: mydomain-mysql
        image: ${REGISTRY_IP}:5000/mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ACC_USER
          value: mydomainadmin
        - name: MYSQL_ACC_PASSWD
          value: "123456"
        - name: MYSQL_SYNC_USER
          value: mydomainslave
        - name: MYSQL_SYNC_PASSWD
          value: "123456"
        - name: MYSQL_MASTER_ADDR
          value: mydomain-mysql-0.mydomain-mysql
        - name: MYSQL_SYNC_FILE
          value: mydomain.000002
        - name: MYSQL_SYNC_POS
          value: "321"
        volumeMounts:
        - name: mydomain-data
          mountPath: /var/lib/mysql
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: mydomain-data
    spec:
      accessModes: [ "ReadWriteOnce"]
      storageClassName: "mydomain-storage"
      resources:
        requests:
          storage: 1Gi